version: '3.6'

services:
  mongo:
    image: mongo:4.0

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: 'http://cypress-inventi-dashboard.herokuapp.com'
      MONGODB_URI: ${MONGO_URI}
      MONGODB_DATABASE: 'cypress-db'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/s3.driver'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_REGION: "us-east-2"
      S3_BUCKET: 'cy-sorry-dashboard'
    ports:
      - 1234:1234
    depends_on:
      - mongo

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: ${MONGO_URI}
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: 'http://cypress-inventi-api.herokuapp.com'
      CI_URL: ''
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
